package ir.ac.itrc.qqa.semantic.enums;

public enum FarsnetSynsetRelationType 
{
	//AGENT, //21
	DIS, //ANTONYM, 1271
	CAUSES, //269
	//CO_OCCURRENCE, //153
	//COORDINATE_TERM, //744
	//DERIVATIONAL_FORM, //162
	//DOMAIN, //231
	//EXCELLENT_ADJECTIVE, //2
	//EXCELLENT_ADJECTIVE_FOR, //145
	//HAS_HOLO_MADE_OF, //3
	//HAS_MERO_MADE_OF, //7
	//HAS_ATTRIBUTE, //5
	//HOLONYM_MEMBER_OF, //169
	//HOLONYM_PART_OF, //870
	//HOLONYM_PORTION_OF, //113
	ISA, //HYPERNYM, 14909
	HYPONYM, //1280
	//INSTRUMENT, //2 
	//IS_AGENT_OF, //3
	//IS_ATTRIBUTE_OF, //2
	IS_CAUSED_BY, //15
	//IS_DOMAIN_OF, //34
	//IS_ENTAILED_BY, //1
	//IS_INSTRUMENT_OF, //71
	//IS_PATIENT_OF, //1
	//MERONYM_MEMBER_OF, //217
	//MERONYM_PART_OF, //894
	//MERONYM_PORTION_OF, //74
	//PATIENT, //17
	RELATED, //related-to: 15024
	//SEE_ALSO, //1
	SIM, //SYNONYM, 42
	GLOSS,
	EXAMPLE,
	USELESS
}
